apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: omnition
    component: otpexp-loadgen-${PROTOCOL}
  name: otpexp-loadgen-${PROTOCOL}
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: otpexp-loadgen-${PROTOCOL}
  template:
    metadata:
      labels:
        component: otpexp-loadgen-${PROTOCOL}
    spec:
      containers:
      - image: 592865182265.dkr.ecr.us-west-2.amazonaws.com/otpexp-loadgen:latest
        imagePullPolicy: Always
        name: otpexp-loadgen-${PROTOCOL}
        command: ["/app/loadgen", "-protocol", "${PROTOCOL}", "-dest", "otpexp-server-${PROTOCOL}:3465"]
        env:
          - name: METRICS_ENDPOINT
            value: "http://prometheus-server.monitoring.svc.cluster.local"

